name: Deploy to Lolipop

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Lolipop
        uses: lolipop-mc/lolipop-mc-dispatch-action@v1
        with:
          api-key: ${{ secrets.LOLIPOP_MC_API_KEY }}
